# ML Service standalone docker-compose for local development
# Run from ml-service directory: docker-compose up -d

services:
  postgres:
    image: postgres:16-alpine
    container_name: ml_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: threads
    ports:
      - '5433:5432'
    volumes:
      - ml_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: ml_ollama
    restart: unless-stopped
    ports:
      - '11434:11434'
    volumes:
      - ml_ollama_data:/root/.ollama
    healthcheck:
      test: ['CMD', 'ollama', 'list']
      interval: 30s
      timeout: 10s
      retries: 3
    # Auto-pull Gemma model on startup
    entrypoint: >
      sh -c "
        ollama serve &
        OLLAMA_PID=$$!
        sleep 5
        ollama pull gemma3:270m
        wait $$OLLAMA_PID
      "

  ml-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_service
    restart: unless-stopped
    ports:
      - '8001:8000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/threads
      PYTHONUNBUFFERED: '1'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'python -c "import socket; socket.create_connection((''localhost'', 8000), timeout=2)" || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - .:/app

  dagster_webserver:
    build:
      context: .
      dockerfile: Dockerfile.dagster
    container_name: ml_dagster_webserver
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/threads
      OLLAMA_BASE_URL: http://ollama:11434
      DAGSTER_HOME: /app/dagster_home
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - ml_dagster_data:/app/dagster_home
    entrypoint:
      - uv
      - run
      - dagster-webserver
      - -h
      - 0.0.0.0
      - -p
      - '3000'
      - -w
      - /app/dagster.yaml
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/server_info']
      interval: 30s
      timeout: 10s
      retries: 3

  dagster_daemon:
    build:
      context: .
      dockerfile: Dockerfile.dagster
    container_name: ml_dagster_daemon
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/threads
      OLLAMA_BASE_URL: http://ollama:11434
      DAGSTER_HOME: /app/dagster_home
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
    volumes:
      - .:/app
      - ml_dagster_data:/app/dagster_home
    entrypoint:
      - uv
      - run
      - dagster-daemon
      - run

volumes:
  ml_postgres_data:
  ml_ollama_data:
  ml_dagster_data: